service: forward-as-email
provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: us-west-2
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "sns:Publish"
      Resource: "arn:aws:sns:us-west-2:439899812822:support-email"
functions:
  support:
    handler: handler.forwardAsEmail
    events:
      - http:
          path: support
          method: post
          cors: true
